source 'https://rubygems.org'


gem 'rails', '5.0.0.1'
gem 'puma'
gem 'pg'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'redis'
gem 'cloudinary', '1.1.0'
gem 'carrierwave'
gem "letter_opener"
gem 'sass-rails'
gem 'jquery-rails'
gem 'uglifier'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'simple_form'
gem 'autoprefixer-rails'
gem 'postmark-rails'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'sticky-rails'
gem 'middleman-robots'

group :development, :test do
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'listen', '~> 3.0.5'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'postmark-rails'
end
