source 'https://rubygems.org'
ruby '3.1.2'


gem 'rails'
gem 'puma'
gem 'pg'
gem 'figaro'
gem 'jbuilder'
gem 'devise'
gem 'redis'
gem 'cloudinary' 
gem 'carrierwave'
gem "letter_opener"
gem 'sass-rails'
gem 'jquery-rails'
gem 'uglifier'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'simple_form'
gem 'autoprefixer-rails'
gem 'postmark-rails'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'sticky-rails'
gem 'middleman-robots'
gem 'binding_of_caller'
gem 'better_errors'
gem 'pry-byebug'
gem 'pry-rails'
gem 'spring'
gem 'listen'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'listen'
  gem 'spring-watcher-listen'
  gem 'listen'
  gem 'spring-watcher-listen'
end