# config/meta.yml
meta_title: "Dantera"
meta_description: "Get your lost items back"
meta_image: "/assets/d-logo-dark.png" # Une image dans votre dossier app/assets/images/
#twitter_account: "@dantera" # indispensable pour les Twitter Cards
