# config/meta.yml
meta_title: "Dantera - Get your lost items back"
meta_description: "Thanks to Dantera, returning lost items is now easy, simple and secure. Try us for free!"
meta_image: "/assets/d-logo-dark.png" # Une image dans votre dossier app/assets/images/
#twitter_account: "@dantera" # indispensable pour les Twitter Cards
